export PATH="$HOME/bin:$HOME/.local/bin:$PATH"
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="x5"
plugins=(git z extract)
source $ZSH/oh-my-zsh.sh

# install zplug
if [[ ! -d ~/.zplug ]];then
    git clone https://github.com/zplug/zplug ~/.zplug
fi

# Zplug Plugins
export ZPLUG_HOME="$HOME/.zplug"
source $ZPLUG_HOME/init.zsh
zplug "zsh-users/zsh-autosuggestions", as:plugin, defer:2
zplug "zsh-users/zsh-syntax-highlighting", as:plugin, defer:2

# Install plugins if there are plugins that have not been installed
if ! zplug check; then
    zplug install
fi
# Then, source plugins and add commands to $PATH
zplug load

# Aliases
alias sz="source ~/.zshrc"
alias ta='tmux a || tmux'
alias s='subl'

case "$OSTYPE" in
  darwin*)  # macOS
    alias pwd='pwd | pbcopy && pbpaste'
    alias vz="subl ~/.zshrc"
    ;;
  linux*)   # Linux
    alias vz="vim ~/.zshrc"
    ;;
  *)
esac

# Preferred editor for local and remote sessions
export EDITOR='vim'
