export PATH="$HOME/bin:$HOME/.local/bin:$PATH"
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="x5"
plugins=(git z extract)
source $ZSH/oh-my-zsh.sh

# install zplug
if [[ ! -d ~/.zplug ]];then
    git clone https://github.com/zplug/zplug ~/.zplug
fi

# Zplug Plugins
export ZPLUG_HOME="$HOME/.zplug"
source $ZPLUG_HOME/init.zsh
zplug "zsh-users/zsh-autosuggestions", as:plugin, defer:2
zplug "zsh-users/zsh-syntax-highlighting", as:plugin, defer:2

# Install plugins if there are plugins that have not been installed
if ! zplug check; then
    zplug install
fi
# Then, source plugins and add commands to $PATH
zplug load

# Aliases
alias sz="source ~/.zshrc"
alias ta='tmux a || tmux'

# Smart editor function
s() {
  local editor=$(command -v subl >/dev/null 2>&1 && echo "subl" || echo "vim")

  if [ $# -eq 0 ]; then
    $editor
    return
  fi

  if command -v "$1" >/dev/null 2>&1; then
    $editor "$(which "$1")"
  else
    [ ! -f "$1" ] && touch "$1"
    $editor "$1"
  fi
}

case "$OSTYPE" in
  darwin*)  # macOS
    alias pwd='pwd | tee >(pbcopy)'
    if command -v subl >/dev/null 2>&1; then
      alias vz="subl ~/.zshrc"
    else
      alias vz="vim ~/.zshrc"
    fi
    ;;
  linux*)   # Linux
    alias vz="vim ~/.zshrc"
    ;;
  *)
    ;;
esac

# Preferred editor for local and remote sessions
export EDITOR='vim'
export TERM=xterm-256color
